name: CI Pipeline  
on: [push, pull_request]  

jobs:  
  test:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Python  
        uses: actions/setup-python@v3  
        with:  
          python-version: 3.x  

      - name: Install dependencies  
        run: pip install pylint  

      - name: Run PyLint on all Python files  
        run: pylint *.py  
        continue-on-error: true

      - name: Run Unit Tests  
        run: python -m unittest discover
